"""Write docs/checks.md from the specifications of the checks of this package.

Run it in the devShell from the repository root:

    nix develop --command uv run python scripts/check_docs.py

With `--check`, it writes nothing, and exits 1 when docs/checks.md is not the file that
it would write. `scripts/check` uses this form.

The checks are the entry points of the group `pulseq_checks.checks` that the
distribution `pulseq-checks` gives. A plugin documents its own checks. The heading of
each check is its ID in backticks, so that the anchor of the heading is the ID without
dots, the anchor that `rules.spec_url` builds.
"""

import argparse
import importlib.metadata
import re
import sys
from pathlib import Path

from pulseq_checks.registry import CHECKS
from pulseq_checks.rules import DOCS_URL, CheckSpec, spec_url

ROOT = Path(__file__).resolve().parent.parent
CHECKS_MD = ROOT / "docs" / "checks.md"
PACKAGE = "pulseq-checks"

INTRODUCTION = """\
A specification says exactly what a check measures, which inputs and models it needs,
its limit and tolerance, and when it passes. Each result of a check of this package has
a link to the heading of its check on this page. The specification has a version, and
the version changes when the rule changes, from the first final release (0.1.0) on. In the
release candidates, each specification is version 1.

This page is generated by `scripts/check_docs.py` from the specifications in the code.
Do not edit it by hand. `scripts/check` fails when the page is not up to date. To make
it again, run `nix develop --command uv run python scripts/check_docs.py`.
"""


def package_specs() -> list[CheckSpec]:
    """The `spec` of each check entry point of this package, sorted by ID."""
    specs = []
    for ep in importlib.metadata.entry_points(group=CHECKS):
        if ep.dist is not None and _canonical(ep.dist.name) == _canonical(PACKAGE):
            specs.append(ep.load().spec)
    return sorted(specs, key=lambda spec: spec.id)


def _canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def anchor(heading: str) -> str:
    """The GitHub anchor of a heading: lower case, punctuation removed except `-`."""
    return re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")


def check_anchors(specs: list[CheckSpec]) -> None:
    """Exit with a message when the anchor of the heading of a check is not the anchor
    in `spec_url`."""
    for spec in specs:
        expected = spec_url(spec)
        if spec.url is not None or expected != f"{DOCS_URL}#{anchor(f'`{spec.id}`')}":
            sys.exit(f"the heading of {spec.id} does not match its URL {expected}")


def as_code(values: tuple[str, ...]) -> str:
    return ", ".join(f"`{value}`" for value in values) or "None"


def section(spec: CheckSpec) -> str:
    """The text of the heading of `spec` and its fields."""
    fields = [
        ("Version", str(spec.version)),
        ("Cost class", spec.cost),
        ("Quantity", spec.quantity),
        ("Inputs", as_code(spec.inputs)),
        ("Models", as_code(spec.models)),
        ("Limit", spec.limit),
        ("Tolerance", spec.tolerance),
        ("Pass condition", spec.pass_condition),
        ("pypulseq function", spec.pypulseq or "None"),
        ("Findings", spec.findings or "None"),
    ]
    lines = [f"## `{spec.id}`", "", spec.title, ""]
    for label, text in fields:
        first, *rest = text.split("\n\n")
        lines += [f"**{label}:** {first}", ""]
        for paragraph in rest:
            lines += [paragraph, ""]
    return "\n".join(lines)


def render(specs: list[CheckSpec]) -> str:
    """The text of docs/checks.md for `specs`."""
    check_anchors(specs)
    index = [f"- [`{spec.id}`](#{anchor(f'`{spec.id}`')})" for spec in specs]
    parts = ["# Checks\n", INTRODUCTION, "\n".join(index) + "\n"]
    parts += [section(spec) for spec in specs]
    return "\n".join(parts).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing, and exit 1 when docs/checks.md is not up to date",
    )
    args = parser.parse_args()
    text = render(package_specs())
    current = CHECKS_MD.read_text(encoding="utf-8") if CHECKS_MD.exists() else None
    if args.check:
        if current != text:
            print(
                "error  docs/checks.md is not up to date. Make it again with "
                "`nix develop --command uv run python scripts/check_docs.py`."
            )
            return 1
        print("ok    docs/checks.md is up to date")
        return 0
    if current != text:
        CHECKS_MD.write_text(text, encoding="utf-8")
    print(f"wrote {CHECKS_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
